### ISSUE TITLE
csv:to-file parsing bug

### ISSUE THREAD

**Issue by jbintz** [NetLogo/CSV-Extension#13]
If item 0 of the list "row" element is a negative number, the number is written as a string.

```
observer> csv:to-file "myfile.csv" [[1 "two" 3] [-4 -5]]
```

will result in a file myfile.csv containing:

```
1,two,3
"-4",-5
```

**Comment by qiemem** [comment]
Thanks for reportering! However, CSV fields don't actually have types. Quotes are only used to keep a field together (in case it has `,` and a newline in it); they don't actually indicate that something is a string. If you open the file in Excel or re-import into NetLogo, the field is correctly interpreted as a number.
