### ISSUE TITLE
Handle boolean literals

### ISSUE THREAD

**Issue by qiemem** [NetLogo/CSV-Extension#2]
Currently, there are the `csv:*-to-strings-and-numbers` reporters. It would be nice if they handled booleans as well.

**Comment by qiemem** [comment]
As part of this, I'm renaming primitives as follows:
- `csv:*-to-strings-and-numbers` to `csv:*-to-list`
- `csv:*-to-strings` to `csv:*-to-string-list`

**Comment by qiemem** [comment]
I'm going to do the renames in a different issue.

**Comment by nicolaspayette** [comment]
How about keeping `csv:*-to-strings` and renaming `csv:*-to-strings-and-numbers` to `csv:*-to-values`?

**Comment by qiemem** [comment]
Good suggestion Nicolas. I've created a new issue for this: #3. See what you think of that scheme. I think @TheBizzle convinced (quite easily) that the parsers that leave things as strings aren't super useful.

**Comment by nicolaspayette** [comment]
Good point. Especially since `map [ (word ?) ]` could be applied if strings were ever needed for some reason.
