### ISSUE TITLE
Clean up API

### ISSUE THREAD

**Issue by qiemem** [NetLogo/CSV-Extension#3]
Current proposed primitives:
- `csv:csv-row-to-strings-and-numbers` -> `csv:from-line`
- `csv:csv-to-strings-and-numbers` -> `csv:from-text`
- `csv:file-to-strings-and-numbers` -> `csv:from-file`
-  `csv:list-to-csv-row` -> `csv:to-line`
- Doesn't exist yet -> `csv:to-text`
- Doesn't exist yet -> `csv:to-file`

And then toss the `*-to-strings` primitives and the readable strings writer.

**Comment by SethTisue** [comment]
is the `from` even needed? how about just `csv:line`, or maybe `csv:read-line`

should `csv:from-text` be `csv:from-string`?

**Comment by TheBizzle** [comment]
I think that the proposed names are sensible.

**Comment by nicolaspayette** [comment]
FWIW: slight preference for `read`/`write` over `from`/`to`, but strong preference for `-string` over `-text`. "Text," to me, connotes words. Seems weird that it could apply to a string like `"1,2,3\n4,5,6"`.

**Comment by qiemem** [comment]
I was thinking `text` to contrast it with `line`. `text` feels larger to me. `line` takes a string as well, so I thought `string` was ambiguous. But I think you've persuaded me.

I was thinking `read/write` might be confused with actual IO operations, where `to-file` and `from-file` are the only actual IO ones.

**Comment by qiemem** [comment]
Alright, I went with the above, except using `string` instead of `text` as suggested.

Still kind of thinking about the `from/to` vs `read/write` thing... but I think I'm happy. Certainly way better than before.
