### ISSUE TITLE
is there any problem with the primitives?

### ISSUE THREAD

**Issue by digitaldust** [NetLogo/CSV-Extension#4]
I am trying to use the csv extensions with the csv:from-file primitive, but it looks like if the primitive does not exist - nor ever the csv:from-line or others... is there something I am missing?

**Comment by qiemem** [comment]
The API is changing from what's in the 5.2 release candidate and the full release. The API in the release candidate can be found here: http://ccl.northwestern.edu/netlogo/docs/csv.html As you'll see, the primitive names were pretty horrifically verbose. When the final version of 5.2 is released, the API shown in this repository will be used. Sorry for the confusion!
