### ISSUE TITLE
NetLogo/CSV-Extension should be the original

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/CSV-Extension#7]
instead of it saying "forked from qiemem/CSV-Extension"

how to sort this out: I guess delete this repo, and then @qiemem transfers ownership of the original to the NetLogo org? but then we lose issues here, so hopefully there's a better way

**Comment by qiemem** [comment]
Would just deleting mine work?

**Comment by SethTisue** [comment]
I'm afraid I don't know

**Comment by SethTisue** [comment]
@qiemem said on Gitter that he's not sure this even needs to happen, so I'm just going to close the issue
