### ISSUE TITLE
Runtime exception when passing list of non-lists to `csv:to-file`

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/CSV-Extension#9]
```
extensions [ csv ]
to go
  csv:to-file "test.csv" [ 1 2 3 ]
end
```

Produces:

```
error (MatchError)
 while observer running CSV:TO-FILE
  called by procedure GO
  called by Command Center

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

scala.MatchError: 1.0 (of class java.lang.Double)
 at org.nlogo.extensions.csv.CSVExtension$ToFile$$anonfun$perform$1$$anonfun$apply$2.apply(CSVExtension.scala:88)
 at org.nlogo.extensions.csv.CSVExtension$ToFile$$anonfun$perform$1$$anonfun$apply$2.apply(CSVExtension.scala:88)
 at scala.collection.Iterator$class.foreach(Iterator.scala:772)
 at scala.collection.immutable.VectorIterator.foreach(Vector.scala:648)
 at org.nlogo.extensions.csv.CSVExtension$ToFile$$anonfun$perform$1.apply(CSVExtension.scala:88)
 at org.nlogo.extensions.csv.CSVExtension$ToFile$$anonfun$perform$1.apply(CSVExtension.scala:87)
 at org.nlogo.extensions.csv.CSVExtension.using(CSVExtension.scala:110)
 at org.nlogo.extensions.csv.CSVExtension$ToFile.perform(CSVExtension.scala:87)
 at org.nlogo.prim._extern.perform(_extern.java:54)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.3.1
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_74 (Oracle Corporation; 1.8.0_74-b02)
operating system: Linux 4.4.0-31-generic (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Untitled

05:01:10.465 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
05:01:10.464 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:01:10.464 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:01:10.463 AddJobEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
05:01:10.463 OutputEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
05:01:10.463 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
05:01:10.461 CompileMoreSourceEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
05:01:10.351 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:01:10.151 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
05:01:09.951 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
```

_Maybe_ the extension could be lenient and interpret `csv:to-file "test.csv" [ 1 2 3 ]` as a demand to write a single row. If it is deemed wiser to refuse such an input, a better error message should at least be given.

**Comment by qiemem** [comment]
I think strictness would be better here. Consider:

```
csv:to-file "test.csv" [
  [1 2 3]
  [4 5 6]
  [7 8 9]
  0
]
```

The lenient approach would result in all data here being placed in a single row, though that is very unlikely to be the intention. That is, it's too easy to mess up the output with a single non-list element (especially if the rows are being generated by a reporter).

An alternative lenient approach would be to skip any non-list elements. This is the current behavior of `csv:to-string`, and matches NetLogo's approach to similar list functions like `sum` and `mean`.

So I think we should either:
1. Strictness: Require every item in the list to be a list, and error otherwise.
2. Leniency: Ignore non-list items in the list.

I'm not sure what I think is better. The advantage of strictness is to avoid the "why is my data not getting saved???" confusion, while the advantage of leniency is a little convenience, and avoiding possible loss of data due to an error after a run (but before you save results or whatever).

I'm leaning towards strictness at the moment. Either can result in a loss of data, and I think it's better to be noisy about that kind of thing.

Though, @nicolaspayette (or anyone else)?

**Comment by nicolaspayette** [comment]
> The lenient approach would result in all data here being placed in a single row, though that is very unlikely to be the intention.

Ugh. Excellent point. I agree that this should rule it out.

> An alternative lenient approach would be to skip any non-list elements. This is the current behavior of `csv:to-string`, and matches NetLogo's approach to similar list functions like `sum` and `mean`.

Hum... it is true for `sum`, but not for `mean` (a lack of consistency that I find troubling!)

> 1. Strictness: Require every item in the list to be a list, and error otherwise.
> 2. Leniency: Ignore non-list items in the list.

I'd vote for strictness too, but then there is consistency with `csv:to-string`, and these two primitives _should_ ideally work in the exact same way.

Is it too late to make `csv:to-string` stricter?

**Comment by qiemem** [comment]
> Is it too late to make csv:to-string stricter?

I don't think so. I'll make them both strict.

**Comment by qiemem** [comment]
Fixed in hexy!

**Comment by SethTisue** [comment]
The silent-skipping behavior of primitives like `sum` goes back to Tufts days and I suggest that we should move towards doing less of it, not more of it.
